# ----
# Site

title: MusicBot-jp
description: Fork元の非公式日本語化サイトです。
url: "https://yamagami2211.github.io/MusicBot-jp/"
logo: 'images/logo.png'
google_analytics_key: G-2EWS5XTDBT
show_full_navigation: true

timezone: Asia/Tokyo
permalink: pretty

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - minor
  - major
